  name: Build STL

# 権限（Artifacts を Upload するのに write が要る）
permissions:
  contents: read
  actions: write

on:
  push:
    paths:
      - '**/*.scad'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04          # ★ 24.04 ではなく 22.04 を指定
    steps:
      - uses: actions/checkout@v4  # 最新版
      - name: Install OpenSCAD
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openscad
      - name: Render all parts to STL
        run: |
          for p in assembly hip_bracket xl330_mount 2xl430_mount upper_leg lower_leg foot_plate waist_frame; do
            openscad -o ${p}.stl brother_robot_complete_with_hinges.scad -D part=\"$p\"
          done
      - name: Upload STL artifacts
        uses: actions/upload-artifact@v4   # v4 に上げても OK
        with:
          name: stl-artifacts
          path: '*.stl'
